services:

  unbound-app:
    image: docker.io/nfrastack/unbound
    container_name: unbound-app
    ports:
      - 53:53
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - CONTAINER_NAME=unbound-app
      - TIMEZONE=America/Vancouver
    networks:
      - services
    restart: always

networks:
  services:
    external: true

