version: '3.7'
services:

  unbound-app:
    image: tiredofit/unbound
    container_name: unbound-app
    ports:
      - 53:53
    volumes:
      - ./config:/config
      - ./logs:/logs
    environment:
      - CONTAINER_NAME=unbound-hostname-app
    networks:
      - services
    restart: always

networks:
  services:
    external: true

