#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service single
SERVICE_NAME="unbound"

check_container_initialized
check_service_initialized init
liftoff

unbound_run
